src/GeekStream.Web/Controllers/UsersController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using GeekStream.Core.Services;
using GeekStream.Core.ViewModels;
using GeekStream.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserService _userService;
        private readonly ArticleService _articleService;

        public UsersController(UserService userService, ArticleService articleService)
        {
            _userService = userService;
            _articleService = articleService;
        }

        [HttpPost]
        public async Task<IActionResult> Subscribe(string id)
        {
            if (ModelState.IsValid)
            {
                await _userService.SubscribeAsync(id);
                return RedirectToAction("Index", "Categories");
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Unsubscribe( string id)
        {
            if (ModelState.IsValid)
            {
                await _userService.UnsubscribeAsync(id);
                return RedirectToAction("Index", "Categories");
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            var users = _userService.GetAllUsers();
            return View(users);
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("[controller]/{id}")]
        public IActionResult UserProfile(string id)
        {
            var user = _userService.GetUserById(id);
            var userViewModel = new UserViewModel
            {
                Id = user.Id,
                UserName = user.FirstName + " " + user.LastName,
                IsSubscribed = _userService.IsSubscribed(_userService.GetCurrentUser(), user.Id),
                UserMail = user.Email,
                Rating = user.Rating,
                Articles = _articleService.FindByAuthorId(id),
                UserIcon = user.Avatar
            };

            return View(userViewModel);
        }
    }
}

src/GeekStream.Web/Controllers/VoteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using GeekStream.Core.Entities;
using GeekStream.Core.Services;

namespace GeekStream.Web.Controllers
{
    public class VoteController : Controller
    {
        private readonly VoteService _voteService;
        private readonly UserService _userService;
        private readonly ArticleService _articleService;
        private readonly CommentService _commentService;

        public VoteController(VoteService voteService, UserService userService, ArticleService articleService, CommentService commentService)
        {
            _voteService = voteService;
            _userService = userService;
            _articleService = articleService;
            _commentService = commentService;
        }

        [HttpPost]
        public async Task<IActionResult> ProcessVotes(int articleId, VoteType type)
        {
            if (User.Identity == null)
            {
                return BadRequest();
            }

            var user = _userService.GetCurrentUser();
            var wasOn = _voteService.CheckIfPostIsVoted(user.Id, articleId, type);

            if (!wasOn)
            {
                await _voteService.CreateOrUpdateVoteOnPost(user.Id, articleId, type);
            }
            else
            {
                await _voteService.RemoveVoteFromPost(user.Id, articleId, type);
            }

            var votes = _voteService.GetRatingForPost(articleId);
            var articleAuthorId = _articleService.GetArticleById(articleId).AuthorId;

            await _articleService.UpdateArticleRatingAsync(articleId, votes);

            var userRating = _userService.GetUserRating(articleAuthorId);
            _userService.UpdateUserRating(articleAuthorId, userRating);

            return NoContent();
        }

        [HttpPost]
        public async Task<IActionResult> ProcessVotesOnReply(int commentId, VoteType type)
        { 
            if (User.Identity == null)
            {
                return BadRequest();
            }

            var user = _userService.GetCurrentUser();
            var wasOn = _voteService.CheckIfReplyIsVoted(user.Id, commentId, type);

            if (!wasOn)
            {
                await _voteService.CreateOrUpdateVoteOnReply(user.Id, commentId, type);
            }
            else
            {
                await _voteService.RemoveVoteFromReply(user.Id, commentId, type);
            }

            var votes = _voteService.GetRatingForReply(commentId);
            var comment = _commentService.FindCommentById(commentId);
            await _commentService.UpdateCommentRating(commentId, votes);

            var userRating = _userService.GetUserRating(comment.ApplicationUserId);
            _userService.UpdateUserRating(comment.ApplicationUserId, userRating);

            return NoContent();
        }
    }
}

src/GeekStream.Web/Views/Shared/_ArticleCard.cshtml
@using GeekStream.Core.Entities
@using Microsoft.EntityFrameworkCore
@model GeekStream.Core.ViewModels.ArticleViewModel;
@{
    var articleId = @Model.Id;
<div class="card mb-2">
    <div class="card-body rounded-lg">
        <div class="card-navbar justify-content-between">
            <div class="navbar-right">
                <a name="category" asp-controller="Categories" asp-action="Index" asp-route-category="@Model.CategoryId">
                <img class="category__icon" width="20" src="/images/@Model.CategoryIcon.FileName"/>
                    @Model.Category
                </a>
                @Html.DisplayFor(modelItem => Model.PublishedDate)
            </div>
            <div class="navbar-left">
                <a asp-controller="Users" asp-action="UserProfile" asp-route-id="@Model.AuthorId">
                <img class="user__icon" width="20" src="/images/@Model.UserIcon.FileName"/>
                    @Html.DisplayFor(modelItem => Model.Author)
                </a>
            </div>
        </div>
        <h3 class="card-title"> @Html.DisplayFor(modelItem => Model.Title)</h3>
        @foreach (var image in Model.Images)
        {
            <img src="~/images/@image.FileName"/>
        }
        <p>@Html.DisplayFor(modelItem => Model.Content)</p>
        <div class="text-right mb-0">
            <form asp-controller="Vote" asp-action="ProcessVotes">
                <input type="hidden" asp-for="@articleId"/>
                <input type="hidden" name="type" value="@VoteType.UpVote"/>
                <input type="submit" class="btn btn-success" value="Upvote"/>
            </form>
            <p>@Html.DisplayFor(modelItem => Model.Rating)</p>
            <form asp-controller="Vote" asp-action="ProcessVotes">
                <input type="hidden" asp-for="@articleId"/>
                <input type="hidden" name="type" value="@VoteType.DownVote"/>
                <input type="submit" class="btn btn-danger" value="Downvote"/>
            </form>
        </div>
        @{
            if (Model.Comments.Any())
            {
                <h5>Комментарии (@Model.Comments.Count())</h5>
                foreach (var item in Model.Comments)
                {
                    var commentId = item.Id;
                    <div class="comment">
                        <div class="comment-navbar">
                            <img/>
                            <b>@item.UserName</b>
                        </div>
                        <div class="comment-body">
                            <span class="comment-text">
                                @item.Content
                            </span>
                        </div>
                        <div class="comment-footer d-flex justify-content-between">
                            <b class="comment-reply">
                                Ответить
                            </b>
        
                            <form asp-controller="Vote" asp-action="ProcessVotesOnReply">
                                <input type="hidden" asp-for="@commentId"/>
                                <input type="hidden" name="type" value="@VoteType.UpVote"/>
                                <input type="submit" class="btn btn-success"/>
                            </form>
                            <p>@Html.DisplayFor(modelItem => item.Rating)</p>
                            <form asp-controller="Vote" asp-action="ProcessVotesOnReply">
                                <input type="hidden" asp-for="@commentId"/>
                                <input type="hidden" name="type" value="@VoteType.DownVote"/>
                                <input type="submit" class="btn btn-danger"/>
                            </form>
                        </div>
                    </div>
                }
            }
            else
            {
                <h5>Комментариев пока нет</h5>
            }
            if (User.Identity.IsAuthenticated)
            {
                <form asp-action="Comment" asp-controller="Articles">
                    <div class="form-row">
                        <div class="col-10">
                            <input type="hidden" name="articleId" asp-for="@Model.Id"/>
                            <input type="text" class="form-control" name="text" placeholder="Ваш комментарий">
                        </div>
                        <div class="col-2">
                            <input type="submit" class="btn btn-outline-light"/>
                        </div>
                    </div>
                </form>
            }
        }
    </div>
</div>
}

src/GeekStream.Web/Views/Shared/_ArticlesListCards.cshtml
@using GeekStream.Core.Entities
@model IEnumerable<GeekStream.Core.ViewModels.ArticleViewModel>

@foreach (var item in Model)
{
  var articleId = item.Id;
    var categoryIcon = item.CategoryIcon.FileName;
    var userIcon = item.UserIcon.FileName;
    <div class="card mb-2">
        <div class="card-body rounded-lg">
            <div class="card-navbar justify-content-between">
                <div class="navbar-right">
                    <a name="category" asp-controller="Categories" asp-action="Index" asp-route-category="@item.CategoryId">
                    <img class="category__icon" width="20" src="/images/@categoryIcon"/>
                        @item.Category
                    </a>
                    @Html.DisplayFor(modelItem => item.PublishedDate)
                </div>
                <div class="navbar-left">
                    <a asp-controller="Users" asp-action="UserProfile" asp-route-id="@item.AuthorId">
                        <img class="user__icon" width="20" src="/images/@userIcon"/>
                        @Html.DisplayFor(modelItem => item.Author)
                    </a>
                </div>
            </div>
            <a asp-controller="Articles" asp-action="Details" asp-route-id="@item.Id">
                <h3 class="card-title"> @Html.DisplayFor(modelItem => item.Title)</h3>
            </a>
            <p>@Html.DisplayFor(modelItem => item.Content)</p>
            <div class="text-right mb-0">
            <form asp-controller="Vote" asp-action="ProcessVotes">
                <input type="hidden" asp-for="@articleId"/>
                <input type="hidden" name="type" value="@VoteType.UpVote"/>
                <input type="submit" class="btn btn-success" value="Upvote"/>
            </form>
            <p>@Html.DisplayFor(modelItem => item.Rating)</p>
                <form asp-controller="Vote" asp-action="ProcessVotes">
                    <input type="hidden" asp-for="@articleId"/>
                    <input type="hidden" name="type" value="@VoteType.DownVote"/>
                    <input type="submit" class="btn btn-danger" value="Downvote"/>
                </form>
            </div>
        </div>
    </div>
}

src/GeekStream.Web/Views/Shared/_ChatsLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="warticleIdth=device-warticleIdth, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeekStream</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_Navbar")
    </header>
    <div class="container">
        <div class="row">
                @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/GeekStream.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="warticleIdth=device-warticleIdth, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeekStream</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @await Html.PartialAsync("_Navbar")
    </header>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                @await RenderSectionAsync("subscriptions", required: false)
            </div>
            <div class="col">
                @RenderBody()
            </div>
            <div class="col-md-3">
                @await RenderSectionAsync("discussingNow",required: false)
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/GeekStream.Web/Views/Shared/_Navbar.cshtml
@using GeekStream.Core.Entities
@using GeekStream.Core.Services
@inject UserService _userService;

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 align-items-center">
            <div class="container h-100">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/NavBarLogo.png" width="50" height="43" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 align-items-center">
                        <li class="nav-item mr-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articles" asp-action="Index">Статьи</a>
                        </li>
                        <li class="nav-item mr-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chats" asp-action="Private">Дискуссии</a>
                        </li>
                        <li class="nav-item mr-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="All">Категории</a>
                        </li>
                        <li class="nav-item mr-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Авторы</a>
                        </li>
                        <li class="nav-item mr-1">
                            <a class="btn btn-primary btn-color" asp-area="" asp-controller="Articles" asp-action="Create">Написать статью</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-controller="Articles" asp-action="Index" method="get">
                                <input type="text" name="SearchString" class="form-control" placeholder="Найти статью">
                            </form>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1 align-items-center">

                    @{
                        if (User.IsInRole("Reviewer"))
                        {
                            <a class="btn btn-outline-info mr-1" asp-area="" asp-controller="Articles" asp-action="Pending">Проверить статьи</a>//TODO ACTION - PENDING
                        }

                        if (User.Identity.IsAuthenticated)
                        {
                            <div class="btn btn-outline-dark mr-1">
                                <a asp-action="Drafts" asp-controller="Articles">Мои черновики</a>
                                </div>
                            var user = _userService.GetCurrentUser();
                            <div class="dropdown">
                                <div class="dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @user.FirstName @user.LastName
                                </div>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-controller="Users" asp-action="UserProfile" asp-route-id="@user.Id">Профиль</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <form class="dropdown-item" asp-controller="Account" asp-action="Logout" method="post">
                                        <button type="submit" class="nav-link btn btn-link text-dark">Logout @user.FirstName</button>
                                    </form>
                                </div>
                            </div>
                        }
                        else
                        {
                            <a asp-area="" asp-controller="Account" asp-action="Login" class="mr-2 btn btn-primary">Войти</a>
                            <a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                        }
                    }
                    </ul>
                </div>
            </div>
        </nav>